name: Github Push back to gitea

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pikaos-linux/pikaos-builder:nestv3
      volumes:
        - /proc:/proc
      options: --privileged -it

    steps:

    - name: Run
      run: ls
