name: Github Push back to gitea

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pikaos-linux/pikaos-builder:nestv3
      volumes:
        - /proc:/proc
      options: --privileged -it

    steps:

    - uses: actions/checkout@v3

    - name: Is github check
      run: echo "${PWD##*/}" | grep "gitea-pika-first-setup" || exit 1

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.GITEA_SSH_KEY }}
        name: id_rsa
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        if_key_exists: replace

    - name: Run
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: ./.github/github_pushback.sh
