name: Github Push back to gitea

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pikaos-linux/pikaos-builder:nestv3
      volumes:
        - /proc:/proc
      options: --privileged -it

    steps:
    - uses: actions/checkout@v3

    - name: Run
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: ./.github/github_pushback.sh "${{ secrets.SSH_PRIVATE_KEY }}"
